### ISSUE TITLE
Evaluation 1950 spinup / control simulation low resolution

### ISSUE THREAD

**Issue by tsemmler05** [tsemmler05/AWI-CM3-HighResMIP#4]
For testing, I started two 1950 spinup / control simulations in low resolutions:

sp1950c: TCO95-CORE2
sp1950f: TCO159-CORE2

Both are started in 1850 with constant 1950 greenhouse gas and aerosol forcing. The first 100 years (1850-1949) are regarded as spin-up. Years 1950-2200 will be regarded as control simulation. Please note that the names of the years of course do not correspond to real years because of the constant forcing.

Good news: Performance in 2025-2049 still slightly better than CMIP6 models although exactly the same tuning has been used as for TCO319-DART. The only difference is that GM is switched on for coarse resolutions and switched off for fine resolutions. One step towards consistent paleo climate dynamics and climate dynamics simulations has been achieved!

**Comment by tsemmler05** [comment]
Performance index sp1950c 2025-2049:
![AWI-CM3-sp1950c_2025_2049](https://user-images.githubusercontent.com/25242072/201609741-cf25eeb6-6f0d-4b77-ba13-5634d74d6b85.png)

Performance index sp1950f 2025-2049:
![AWI-CM3-sp1950f_2025_2049](https://user-images.githubusercontent.com/25242072/201609827-950c36e1-6a5a-4a99-9508-9fa199bdcf23.png)

**Comment by JanStreffing** [comment]
Interesting to see how little improvement the switch from TCo95 to TCo159 makes. This is also what I found between release v3.0 and v3.1 when I decided to lower the paleo atmospheric resolution.

The one place I see a large difference is in the 1000m salinity and temperature in the arctic. Considering that we use the same ocean model, this is rather surprising to me. I wonder what happened there.

**Comment by tsemmler05** [comment]
One needs to consider that the results are up to 200 years after initialization. Some internal variability or influences from the higher-resolved mid-latitude atmosphere on the mid-latitude ocean that may propagate into the Arctic could play a role here. More likely just internal variability. Can be easily checked in considering other time periods. Will most probably perform the transient simulation from 1950-2200 with the TCO95-CORE2 version.

**Comment by tsemmler05** [comment]
The ocean seems to accumulate more heat in the low resolution versions compared to the high resolution version:

surface energy balance years 2025-2049 TCO95-CORE2: 1.12 W/m2
surface energy balance years 2025-2049 TCO159-CORE2: 0.98 W/m2
(surface energy balance years 1850-1859 TCO319-DART: 0.64 W/m2)

**Comment by tsemmler05** [comment]
This shows the globally averaged heat accumulation in sp1950c (TCO95-CORE2) especially in around 500 m depth over the first 60 years of the simulation (while the surface is too cold):

![awicm3_sp1950c_hovm_difference_clim_Global_Ocean_temp png](https://user-images.githubusercontent.com/25242072/201636592-5a359176-c571-4842-a927-9f7796fa3302.png)

**Comment by tsemmler05** [comment]
The SST in TCO95-CORE2 looks amazingly well (here years 2000-2059) - especially regarding Southern Ocean warm bias:

![awicm3_sp1950c_climatology_temp_0](https://user-images.githubusercontent.com/25242072/201682961-c7bcfa61-7fa7-4112-aec8-084abb5c6fc4.png)

**Comment by tsemmler05** [comment]
While in 500 m the strong warm bias can be seen (as was expected from Hovmöller plot two posts above) in years 2000 to 2059: 

![awicm3_sp1950c_climatology_temp_500](https://user-images.githubusercontent.com/25242072/201683331-c3762b4e-9ad7-468c-a1fe-c61785c6e3b5.png)

**Comment by wonsunp** [comment]
Great to see the two resolutions! Thank you very much for making this available. I would like to see the evolution of the AMOC and ACC, and could you make it or help Dae-Won to process it?

**Comment by wonsunp** [comment]
What is the time step of the OpenIFS for these configurations?

**Comment by tsemmler05** [comment]
Time step for both TCO95 and TCO159 is 3600s. AMOC I can post later; in any case the data are available here: /scratch/awiiccp5/sp1950c/outdata (TCO95-CORE2) and /scratch/awiiccp5/sp1950f/outdata (TCO159-CORE2)

**Comment by tsemmler05** [comment]
This is the AMOC averaged over the years 2000-2059 for sp1950c (TCO95-CORE2):

![awicm3_sp1950c_xmoc_Atlantic_MOC](https://user-images.githubusercontent.com/25242072/201883924-3579a494-4825-4506-81b7-166da65eb3d1.png)

**Comment by tsemmler05** [comment]
The energy imbalance of around 1 W/m2 takes its toll. The deeper ocean is warming up while the surface remains comparably cool and the warm water is upwelling around Antarctica. Therefore, the sea ice extent development over the 350 years of simulation looks like this (Southern sea ice extent still declining while Northern sea ice extent in quasi-equilibrium):

![awicm3_sp1950c_ice_integrals_combined_iceext_combined](https://user-images.githubusercontent.com/25242072/202181444-ec7514cf-1637-477f-8ebe-58ac30d534b1.png)

**Comment by tsemmler05** [comment]
This looks similar but a bit less pronounced (consistent with slightly smaller energy imbalance) in sp1950f (TCO159L91-CORE2)
![awicm3_sp1950f_ice_integrals_combined_iceext_combined](https://user-images.githubusercontent.com/25242072/203072738-e8cde679-c890-4a26-bbdd-62e2d325a3a8.png)
